services:

    drupal.compat.argument_resolver:
        public: false
        class: MakinaCorpus\Drupal\Sf\HttpKernel\Controller\ArgumentResolver\DrupalArgumentResolver
        tags: [{name: controller.argument_value_resolver, priority: -100}]
